### ISSUE TITLE
Cool!  What is it?  :)

### ISSUE THREAD

**Issue by johnbent** [00pauln00/yapio#1]
Just curious about what this benchmark is. What it is measuring. What was missing in IOR and mdtest to motivate its creation.

**Comment by 00pauln00** [comment]
The main difference is that it allows for running of multiple jobs within a
single mpi scope.  It also does data checking by default, which is useful
for ensuring that file out of core data exchanges done properly.

**Comment by 00pauln00** [comment]
Here's some stuff from the help:

-t  Test description
   - Pattern:    sequential (s), random (R), strided (S)
   - I/O Op:     read (r), write (w)
   - Locality:   local (L), distributed (D)
   - Options:    backwards (b), holes (h), no-fsync (f)
   - Parameters: block size (B), blocks per rank (n),
                 num ranks (N), file-per-process (F)

   Example: -t wsL,rRD
     sequential write, distribute reads randomly

   Example: -t wsL,rRD -t N4:B4096:F:ws,rsb
     Run two tests simultaneously


In the first example, each rank writes sequentially during the first
iteration and on the second iteration each rank randomizes its block list
and exchanges with the others to determine the read assignments.

These test descriptions can have lots of different combinations too:

-t wsL,rsb,wSL,rRD -> this one writes, reads sequential, writes strided,
and then reads randomly.  Each read iteration ensures the integrity of file
data..

From there you can add more test descriptions to the command line:

-t wsL,rsb,wSL,rRD -t ws,rs -> this test will split your mpi ranks in half
and each half will simultaneously run its prescribed test description to
completion.

Each test description can get its own block, num blocks, num ranks, and
file options too:

-t wsL,rsb,wSL,rRD -t N10:B1024:n100000000:F:ws,rs,rSR -> test 2 will use
10 ranks, with a block size of 1k, and use file-per-process.  In the file
per process mode, the 'rSR' test will cause a strided read pattern across
all files - so each rank will strided across the whole data space not just
its file.


I think that sums it up..
p

**Comment by johnbent** [comment]
Why's it called YapIO by the way?  Yap is a cool Pacific Island but not
well known for IO.

**Comment by 00pauln00** [comment]
'yet another parallel I/o (tester)'
