### ISSUE TITLE
Compilation produces a warning 

### ISSUE THREAD

**Issue by 00pauln00** [00pauln00/yapio#3]
(pauln@samael:~/Code/yapio)$ make 
mpicc -o yapio yapio.c -Wall -Wextra -O2 -lpthread
yapio.c: In function ‘yapio_initialize_source_md_buffer_from_file’:
yapio.c:1302:14: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(yapioSourceBlkMd, sizeof(yapio_blk_md_t), nblks_per_rank, file);
              ^

**Comment by Nicolas-Triquenaux** [comment]
travis for compilation tasks ?
